/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "onkqodvrlkhvribbsvhp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ua3FvZHZybGtodnJpYmJzdmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NTk5MDgsImV4cCI6MjA3ODMzNTkwOH0.UchsSobWVeY3RNgd7KpRCh0fbAc-NlP2xF-UHG0flgM"